baseURL = "http://example.org/"
languageCode = "en-us"
title = "PowerShell Southampton"
theme = "ananke"

[params]
    twitter = "https://twitter.com/codaamok"
    github = "https://github.com/codaamok