baseURL = "https://ambitious-dune-03065f303.azurestaticapps.net/"
languageCode = "en-us"
title = "PowerShell Southampton"
theme = "ananke"
themesDir = "../.."

[params]
    favicon = ""
    site_logo = ""
    description = "The last theme you'll ever need. Maybe."
    twitter = "https://twitter.com/codaamok"
    github = "https://github.com/codaamok
    background_color_class = "bg-black"
    featured_image = "/images/gohugo-default-sample-hero-image.jpg"
    recent_posts_number = 2 
