baseURL = "https://storagepssouth.z33.web.core.windows.net/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend-ng"

[params]
    description = "A PowerShell user group based in the south of UK."
    homeSubtitle = "A PowerShell user group based in the south of UK."
    enableSharingButtons = true
    disableReadOtherPosts = false
    images = [""]

[taxonomies]
    tag      = "tags"
    category = "categories"

[languages]

    [languages.en]
        title = "PowerShell Southampton"
        subtitle = "UK"
        keywords = "PowerShell"
        copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
        readOtherPosts = "Read other posts"

        [languages.en.params.logo]
            logoText = " "
            logoHomeLink = "/"
    
    [[menu.main]]
        identifier="about"
        name="about"
        url="/about"

    [[menu.main]]
        identifier="events"
        name="events"
        url="/events"

    [[menu.main]]
        identifier="sponsors"
        name="sponsors"
        url="/sponsors"

    [[menu.main]]
        identifier="codeofconduct"
        name="code of conduct"
        url="/codeofconduct"

[deployment]

    [[deployment.targets]]
        name = "mydeployment"
        URL = "azblob://$web"