baseURL = "https://new.pssouth.co.uk/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend-ng"

[params]
    description = "A PowerShell user group based in the south of UK."
    homeSubtitle = "A PowerShell user group based in the south of UK."
    enableSharingButtons = true
    disableReadOtherPosts = true
    images = [""]

    footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
    footerRight = "Hosted in <a href=\"https://azure.microsoft.com\">Azure</a>"

    [[params.social]]
        name = "twitter"
        url  = "https://twitter.com/PSSouthampton"

    [[params.social]]
        name = "youtube"
        url  = "https://youtube.com/c/PowerShellSouthampton"

    customCSS = ["css/custom.css"]

[taxonomies]
    tag      = "tags"
    category = "categories"

[languages]
    [languages.en]
        title = "PowerShell Southampton"
        subtitle = "UK"
        keywords = "PowerShell"

        [languages.en.params.logo]
            logoText = " "
            logoHomeLink = "/"
    
[menu]
    [[menu.main]]
        identifier="about"
        name="about"
        url="/about"

    [[menu.main]]
        identifier="posts"
        name="events"
        url="/posts"

    [[menu.main]]
        identifier="sponsors"
        name="sponsors"
        url="/sponsors"

    [[menu.main]]
        identifier="codeofconduct"
        name="code of conduct"
        url="/codeofconduct"

[deployment]
    [[deployment.targets]]
        name = "Azure"
        URL = "azblob://$web"