name: Azure Storage Blob Container CI/CD

on:
  push: 
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      # Set timezone so .Date.Format renders dates in posts as GMT/BST
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/London"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          hugo version
          hugo -F

      - name: Azure Blob Upload
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az storage blob delete-batch --source "\$web" --sas-token "${{ secrets.AZURE_STORAGE_BLOB_SAS_CONNECTIONSTRING }}" --account-name "storageaccountpssouth"
            az storage blob upload-batch --destination "\$web" --source "./public" --content-cache-control "no-cache, max-age=86400" --sas-token "${{ secrets.AZURE_STORAGE_BLOB_SAS_CONNECTIONSTRING }}" --account-name "storageaccountpssouth"
